spring:
  application:
    name: kafka-push
  kafka:
    bootstrap-servers: http://192.168.0.230:9093
    consumer:
      group-id: push-worker-group
      auto-offset-reset: earliest
      properties:
#        schema.registry.url: http://localhost:8081
        schema.registry.url: http://192.168.0.230:8080/ui/artifacts
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    listener:
      missing-topics-fatal: false # Topic? ???? ?????? ?? ??

push:
  fcm:
    url: https://fcm.googleapis.com/v1/projects/YOUR_PROJECT_ID/messages:send
    server-key: YOUR_FCM_SERVER_KEY
  apns:
    url: https://api.push.apple.com
    auth-token: YOUR_APNS_AUTH_TOKEN
